### ISSUE TITLE
Review models for our project

### ISSUE THREAD

**Issue by Grutschus** [Grutschus/human-fall-detection#5]
- [x] Read into the literature to find models suitable for our project
- [x] Document why these models are suitable
- [x] Choose one of the models implemented in MMAction2 that we can use

- [x] (Optional) Draft up da paragraph for this model selection for the final report.

**Comment by emiresenov** [comment]
Thanks for the heads up, I will start digging into this tomorrow as I am currently busy typing up a draft for my thesis proposal.

I'll have to find out more, but at first glance, the lack of variety and the age of the models seems a bit worrying(?) – I'd be curious to find out how they perform on various datasets. Hopefully the few models have something to offer, otherwise it would suck to go for a temporal action implementation and not have good models to go off of.

**Comment by emiresenov** [comment]
I've been reviewing models today. Something that I'm wondering about is whether temporal action localization is an appropriate choice for human fall detection specifically. 

Looking at the models available in MMAction2, they seem to address the problem of temporal-action proposal generation (TAPG). The popular benchmarks for that problem are THUMOS-14 and ActivityNet-1.3. These datasets include large sets of videos with highly varying scenes, scenarios, and actions.

My impression is that TAPG is a hard problem to solve, and the accuracies for state of the art models do not seem to be very high, especially compared to what human fall detection (HFD) algorithms seem to be able to produce.

I’d be curious to see how TAPG performs on human fall datasets specifically, but I wonder if we’re running the risk of taking an overly generalized solution (TAPG) and applying it to something very specific (HFD), losing a lot of accuracy in the process only to get the temporal features.

**Comment by emiresenov** [comment]
For the models available in MMAction2, the TCANet paper did a comparison with the other two models and their model outperformed BSN and BMN, so that would be the model to go for if we're opting for TAPG and the MMAction2 framework.
